---
title: "Spp exploration - threatened status"
format: 
  html:
    embed-resources: true
execute:
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(terra)
library(sf)
library(rnaturalearth)
library(here)
library(iucnredlist) ### remotes::install_github("IUCN-UK/iucnredlist")
```

## Gather data and test IUCN API

Grab a sample of species (5 spp for each taxon) and test out IUCN API

### Identify species sample

```{r}
here_anx <- function(f = '', ...) { 
  ### create file path to git-annex dir for project
  f <- paste(f, ..., sep = '/')
  f <- stringr::str_replace_all(f, '\\/+', '/')
  f_anx <- sprintf('/home/shares/usgs-cap-rangeshifts/data_lawler_2020/%s', f)
  return(f_anx)
}
```

List all map files available, and gather info on species, taxon, and scenario from the file path information.

```{r}
spp_mapfiles <- list.files(here_anx('species_projections'), 
                           full.names = TRUE, recursive = TRUE, pattern = '.tif')
spp_all_df <- data.frame(f = spp_mapfiles,
                         spp = basename(spp_mapfiles) %>%
                           str_remove('(_gf85|_in85|_mc85|_bias).+') %>%
                           str_replace_all('_', ' '),
                         tax = basename(dirname(spp_mapfiles)))

### sample 5 species per taxon, and identify all scenario maps for each
set.seed(16)
spp_sample_df <- spp_all_df %>%
  select(-f) %>%
  distinct() %>%
  group_by(tax) %>%
  slice_sample(n = 5) %>%
  ungroup() 
  #left_join(spp_all_df)
```

### Pull IUCN threat status

We'll use the IUCN api (key required) and their R package (iucnredlist)

```{r}
api_key <- Sys.getenv("IUCN_API_KEY") ### usethis::edit_r_environ() to add key to R environment file
api <- init_api(api_key)
```

```{r}
# Test out getting threat information for a single species (not case sensitive)
spp_test <- assessments_by_name(api, genus = "Canis", species = "lupus")

# Looking at spp_test, the latest global assessment is assessment ID 247624660
assessment <- assessment_data(api, 247624660)
assessment_clean <- parse_assessment_data(assessment)
```

```{r}
# Test to filter the spp_test df for the latest global threat level for the species
spp_latest_threat <- spp_test %>% 
  filter(scopes_code == 1) %>% 
  filter(year_published == max(year_published))
```

```{r}
# Will need to split spp name into genus and species for redlist package
spp_gns_sample_df <- spp_sample_df %>% 
  separate(spp, into = c("genus", "species"), sep = " ")

spp_sample_vec <- spp_gns_sample_df$species
gns_sample_vec <- spp_gns_sample_df$genus
```

```{r}
# Write a function to get the most recent, global iucn status for a species
iucn_status <- function(api, genus, species){
  # get species info 
 species_info <- assessments_by_name(api, genus, species) 
 list_status <- species_info %>% 
   filter(scopes_code == 1) %>% 
   filter(year_published == max(year_published))
 return(list_status$red_list_category_code)
}
```

```{r}
# Test function
# Species 10 (Ptilogonys cinereus does not work) --> need to look into
iucn_status(api, gns_sample_vec[9], spp_sample_vec[9])
iucn_status(api, 'Ptiliogonys', 'cinereus')
### Ptiliogonys cinereus (typo in the data) seems to work!  but we can bet there will be other typos
```

```{r}
# Loop through function
iucn_status_test <- for(i in 1:9){
  test <- iucn_status(api, gns_sample_vec[i], spp_sample_vec[i])
  print(test)
}
```

```{r}
# Loop through function, save as list
iucn_status_list <- list()
for(i in 1:9){
  test <- iucn_status(api, gns_sample_vec[i], spp_sample_vec[i])
  iucn_status_list[[i]] <- test
}
```

